---
title: "Assignment 1"
author: "Binish Kurian Chandy"
date: "8/30/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem Set 1

1. Calculate the dot product u.v where u = [0.5; 0.5] and v = [3; -4]
```{r}
u <- matrix(c(0.5, 0.5), nrow = 2, ncol = 1)
v <- matrix(c(3, -4), nrow = 2, ncol = 1)
u[1,1] * v[1,1] + u[2,1] * v[2,1]
```

2. What are the lengths of u and v? Please note that the mathematical notion of 
the length of a vector is not the same as a computer science definition.
```{r}
u <- matrix(c(0.5, 0.5), nrow = 2, ncol = 1)
v <- matrix(c(3, -4), nrow = 2, ncol = 1)
(length.u <- sqrt(u[1,1]*u[1,1] + u[2,1]*u[2,1]))
(length.u <- sqrt(v[1,1]*v[1,1] + v[2,1]*v[2,1]))
```

3. What is the linear combination: 3u - 2v?
```{r}
u <- matrix(c(0.5, 0.5), nrow = 2, ncol = 1)
v <- matrix(c(3, -4), nrow = 2, ncol = 1)
3*u - 2*v
```

4. What is the angle between u and v
```{r}
(theta <- acos( sum(u*v) / ( sqrt(sum(u * u)) * sqrt(sum(v * v)) ) ))
```

## Problem Set 2
```{r}
elimination <- function(A, b){
        
        pivot <- A[1,1]
        
        if (pivot == 0){
                A <- A[c(2,1,3),]
                pivot <- A[1,1]
                if (pivot == 0){
                        A <- A[c(3,2,1),]
                        pivot <- A[1,1]
                }
        }
        
        mplyr_1 <- A[2,1]/pivot
        mplyr_2 <- A[3,1]/pivot
        
        A[2, ] <- A[2, ] - mplyr_1 * A[1, ]
        b[2,] <- b[2,] - mplyr_1 * b[1,]
        
        A[3, ] <- A[3, ] - mplyr_2 * A[1, ]
        b[3,] <- b[3,] - mplyr_2 * b[1,]
       
        pivot_1 <- A[2,2]
        
        if (pivot_1 == 0){
                A <- A[c(1,3,2),]
                pivot_1 <- A[2,2]
        }
        
        mplyr_3 <- A[3,2]/pivot_1
        
        A[3, ] <- A[3, ] - mplyr_3 * A[2, ]
        b[3,] <- b[3,] - mplyr_3 * b[2,]
        
        
        x3 <- b[3] / A[3, 3]
        
        
        x2 <- (b[2] - A[2, 3] * x3) / A[2, 2]
        
        x1 <- (b[1] - A[1, 3] * x3 - A[1, 2] * x2) / A[1, 1]
        
        
        x <- matrix(c(x1, x2, x3), nrow = 3)
        x
}
# With 0 pivot
A<- matrix(c(0, -3, -1, 1, 1, 3, -1, -2, 4), nrow = 3, ncol = 3, byrow = TRUE)
b <- matrix(c(0, 1, 6),nrow=3,ncol=1)
elimination(A,b)

A <- matrix(c(1, 1, 3, 2, -1, 5, -1, -2, 4), nrow = 3, ncol = 3, byrow = TRUE)
b <- matrix(c(1, 2, 6),nrow=3,ncol=1)
elimination(A,b)
```